### ISSUE TITLE
Shared Data Information

### ISSUE THREAD

**Issue by Umair1181** [react-native-share/react-native-share#1051]
## Ask your Question

I have to post data on social platform and save shared data link or Id in my database...
But react-native-share does not return "postId" ? its is null so any solution in this regard ?

**Comment by mikehardy** [comment]
I don't believe the apps themselves return anything about the share
This is a verifiable assertion: react in to node_modules, into the code from this module, and add some console output for the native platform you're testing (e.g. add some `System.err.println(<whatever the native Java API returns from sharing here>)` and re-test it. See what you get, if anything.

Since I don't believe you get anything, I don't believe there is anything for this module to do.

If I'm wrong and you see some return values or you can find an API document from the apps you are sharing to that explains how to get it, you can post a PR here that returns that data, then store that in your database

**Comment by Umair1181** [comment]
ShareDialog

> 
> 
> I don't believe the apps themselves return anything about the share
> This is a verifiable assertion: react in to node_modules, into the code from this module, and add some console output for the native platform you're testing (e.g. add some `System.err.println(<whatever the native Java API returns from sharing here>)` and re-test it. See what you get, if anything.
> 
> Since I don't believe you get anything, I don't believe there is anything for this module to do.
> 
> If I'm wrong and you see some return values or you can find an API document from the apps you are sharing to that explains how to get it, you can post a PR here that returns that data, then store that in your database

Actually i have to make Facebook post or story and have to store its call back response in case if it return postId or url of post, 
but react-native-share is other app single way working thing, so i'm trying to do it with {ShareDialog} from react-native fbsdk, 
but still is missing the post id...
![image](https://user-images.githubusercontent.com/45887934/125396531-1af18e00-e3c6-11eb-8723-7faac18cae83.png)
