### ISSUE TITLE
Unable to share Text with Images on Facebook and Instagram

### ISSUE THREAD

**Issue by karna419** [react-native-share/react-native-share#1108]
## Ask your Question

Is it possible to share images with Text as post content on Facebook & Instagram?

**Comment by keermanish** [comment]
Sorry but, What is the conclusion here? why this query marked as closed?

**Comment by mikehardy** [comment]
@keermanish it's closed because it went stale. Open source means in general, if people are interested they'll do the work. And if they're not, things go stale and close out (but are still here so they are searchable). Roll up your sleeves to check the available platform native APIs you interact with in the module, instrument the native code or javascript code to see what it's doing, and if you can find a solution post a PR, then it's merge and release time
