### ISSUE TITLE
Share.open Email address not attached on iOS

### ISSUE THREAD

**Issue by Relax594** [react-native-share/react-native-share#1117]
### Steps to reproduce
1. Run the code
```
const sharePdf = mail => {
 const shareOptions = Platform.select({
 default: {
  subject: "This is a test",
  message: "Message content",
  email: "testuser@test.com",
 },
});

Share.open(shareOptions);
};
```
2. Pick Mail in Pop-Up

### Expected behaviour
Email address working on both iOS and Android.

### Actual behaviour
Email address is not getting attached on iOS. Working fine on Android.
![grafik](https://user-images.githubusercontent.com/22765758/138471310-acfa5cda-c60a-44c1-a9c9-22b2d943eb82.png)

### Environment
- **React Native version**: 0.66.1
- **React Native platform + platform version**: iOS 15.0.2, Android 11.0

### react-native-share
**Version**: 7.2.0

**Comment by dimaokk** [comment]
> I'm sorry I couldn't fix this with my PR, I ended up giving up with the `share` API and updated the `shareSingle` instead.

Can you tall me How did you decide this problem.

**Comment by Sachin-kulal** [comment]
Hello,
On Android, the recipient email address is correctly populated when sharing via email, but on iOS, the recipient field remains empty. This issue persists even after updating to the latest react-native-share version (12.0.9).

Steps to Reproduce:

Add an email address in the share options.
Share via the Mail app on iOS.
Expected Behavior:
The recipient field in the Mail app should be pre-filled with the provided email address.

Actual Behavior:
The recipient field is empty in the Mail app on iOS.

Environment:

React Native version: 0.70.0
Platform + version: iOS 12.4.4
react-native-share version: 10.2.1 (also tested on 12.0.9)
Note:
The functionality works correctly on Android but fails on iOS.
