### ISSUE TITLE
Sharing an image via Twitter is broken

### ISSUE THREAD

**Issue by yawnr** [react-native-share/react-native-share#1154]
### Steps to reproduce
1. on iOS, call `Share.shareSingle` with a local image URI as the `url` param. It will load the tweet with that local file URI in the text of the tweet, e.g.
```
      Share.shareSingle({
        message: 'Hello World',
        social: Share.Social.TWITTER,
        url: <LOCAL_FILE_URI>,
        type: 'image/png',
      });
```
2. install an older version (e.g. `6.3.0`), do the same thing and it will work.
3. as a workaround, converting the image to a base64 image and then calling `Share.shareSingle` still works. Is this expected behavior? Seems like a regression from https://github.com/react-native-share/react-native-share/pull/1120

### Expected behaviour
the tweet loads with the image as an image

### Actual behaviour
the tweet loads with the image URI as text

### Environment
- **React Native version**: tested on 64 and 67
- **React Native platform + platform version**: iOS 14 + iOS 15
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?

### react-native-share
**Version**: 7.3.4 (broken) and 6.3.0 (works)

**Comment by mikehardy** [comment]
@yawnr what did you see when you checked the diff in the relevant files from 7.3.4 to 6.3.0? Typically each version is a tiny tiny change, so it should be possible for you to isolate the problem visually even, looking at the git history of the file on the github web UI

**Comment by yawnr** [comment]
hey @mikehardy - yeah i went through each release's diff and it seems like the only change to the twitter sharing was the PR i linked above, but i then reverted that diff manually in my `node_modules` and re-built and it didn't fix it so i was at a bit of a loss. let me do a little more testing on the versions surrounding that change and get back to you.

**Comment by sfuqua** [comment]
Same experience on the latest version - sharing a local image results in sharing the URI as text. 7.3.1 (before the iOS twitter changes) shares the image properly.

**Comment by mikehardy** [comment]
:thinking: well, 2 points is a line  you can imagine pointing to something...
So we have two reports that 7.3.1 (or, at least < 7.3.4) works.
We have one manual attempt to back out the twitter change, without success, but not really a commit bisect
We have one report it works with no information on whether it was a full version bisect or (even better) a git commit bisect) to find the offending root cause.
Would be great to know what the actual thing is here and get a patch :pray:

**Comment by rusakovic** [comment]
Confirm the issue on iOS.
Share URL and Message both as text.
On Android - share nothing, only opens Create new tweet in Twitter app.

**Comment by Dakuan** [comment]
still a thing...

**Comment by likeaj6** [comment]
having this issue still on the latest release (7.7.0)
tried both passing image both as a data-uri format (base64) and local file

**Comment by geroale** [comment]
Same issue here

**Comment by mikehardy** [comment]
@geroale those comments don't advance the state of the issue - in order for anything to get fixed in the open source world, a motivated person with a personal interest needs to dig in to the code, check API docs, perform tests, gather results and :sparkles: open a PR :sparkles: 

Anything else is just cluttering notifications and inboxes

**Comment by geroale** [comment]
This is related to https://github.com/react-native-share/react-native-share/issues/1285

The issue is with this line.
https://github.com/react-native-share/react-native-share/blob/86feccc17845864467ae3f026d663a5fd0ed0823/ios/GenericShare.m#L20

The code is not going into the if statement because of the second condition and the exclamation dot in the first (as said here https://github.com/react-native-share/react-native-share/issues/1285#issuecomment-1265184465).

One way to temporary workaround this, at least for me, is to change the if statement from
`if(![serviceType isEqualToString:@"com.apple.social.twitter"] && [[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:inAppBaseUrl]]) {`
to
`if([serviceType isEqualToString:@"com.apple.social.twitter"]) {`

**Comment by geroale** [comment]
@mikehardy It took just 5 minutes to find this.

**Comment by mikehardy** [comment]
@geroale fantastic! We can merge and release any reasonable PRs

**Comment by geroale** [comment]
I guess https://github.com/react-native-share/react-native-share/pull/1315
