### ISSUE TITLE
Utils.m reference in the RNShare.xcodeproj file breaks my build

### ISSUE THREAD

**Issue by swapzone** [react-native-share/react-native-share#1180]
## Ask your Question
First of all I wanted to say thank you for your amazing work!

Second I wanted to report an issue, which I'm not sure is my fault or a problem with the library. I have an issue with the `Utils.m` file being referenced in the `RNShare.xcodeproj` file. I linked one of the references as an example:
https://github.com/react-native-share/react-native-share/blob/main/ios/RNShare.xcodeproj/project.pbxproj#L10

This breaks my build in Xcode since it tries to access the non-existent Utils.m file. Is there something I missed or is it a problem with the library?

I would highly appreciate your help with that!

**Comment by mikehardy** [comment]
Fascinating! How did it only break your build now, when it has been working since this PR in July of 2021?!? :thinking: 

#1060 - where it was moved from Utils.[h|m] to RNShareUtils.[h|m]

What happens when you edit that file pbxproj file locally to be RNShareUtils instead of Utils ? If it works you may use patch-package to keep you working locally and post a PR here

**Comment by swapzone** [comment]
Thanks a lot for your quick reply! I figured that it does work when I edit the file locally so I'm not blocked on this. I'll post a PR in the next couple of days!

**Comment by syllomex** [comment]
I am facing the same issue. It started after I followed the manual [iOS installation guide](https://react-native-share.github.io/react-native-share/docs/install#ios-install).
Before that it wasn't happening, but the shareSingle to WhatsApp was throwing the error on #555

**Comment by mikehardy** [comment]
I maintain my initial two reactions: 1) I am astonished this is just coming up now but 2) this is obviously an error just via visual inspection. I do about 4k changes on github a year and I haven't seen this ever. Software is always surprising :laughing: 

I just posted #1183 which contains what *seems* to be the obvious fix. @swapzone if you indicate that looks like what you did, or @syllomex if you can try it, we can merge+release this

**Comment by swapzone** [comment]
I'm testing this fix right away. My approach to fix this was in the Xcode UI directly instead of changing the file. But I'm in the process of reproducing this scenario right now.

**Comment by mikehardy** [comment]
Shouldn't be necessary if auto-linking is used vs manual project addition per related PR comments and doc ref https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

Going to close but as mentioned on related PR comments: that's with the idea that if you use react-native CLI auto-linking this should be working. That's why it has been hiding in plain site for nearly a year - it works fine in supported module integration style (auto-linking)

**Comment by syllomex** [comment]
I reinstalled it with auto-linking. It worked, but looks like the ```url``` param is required on iOS. The "nil argument" exception stopped as I passed an empty string to url

**Comment by mikehardy** [comment]
@syllomex :thinking:  - glad you have it working now - perhaps if there is a documentation change needed for whatsapp (to indicate URL is mandatory) you could hit the edit button on the related doc and propose a PR? I haven't shared to whatsapp specifically (I just do a general share) so it's not a use case of mine and I have not / would not notice.
