### ISSUE TITLE
Anybody knows how to make attributionURL / contentURL to work with stories?

### ISSUE THREAD

**Issue by ferrannp** [react-native-share/react-native-share#1265]
## Ask your Question

Hello 👋 

I was trying to share images as stories on Instagram and Facebook. Everything is fine. However i cannot make the `attributionURL` to work successfully.

Instagram stories code: https://github.com/react-native-share/react-native-share/blob/d3cfaefaf356b7fa99b142cde53e9f509ec859dd/ios/InstagramStories.m#L49-L52
Facebook stories code: https://github.com/react-native-share/react-native-share/blob/d3cfaefaf356b7fa99b142cde53e9f509ec859dd/ios/FacebookStories.m#L52-L55

My understanding is that users could click in what you share to be linked somewhere? Like a web or your app? 

Has anybody manage to make this work? Any instructions? (I could not find them in the [official Meta docs](https://developers.facebook.com/docs/instagram/sharing-to-stories)).

**Comment by tsaomaxwell** [comment]
https://stackoverflow.com/questions/44283082/url-scheme-to-post-to-instagram-stories
b_ray states in the comments of the above stack overflow that the attribution url was originally a closed beta feature which has since been removed from documentation. My guess is that Meta ended up removing this feature from their API entirely, so this may no longer be possible

**Comment by DineshK-1** [comment]
This was officially a "closed beta" feature and appears to have been removed from the [documentation](https://developers.facebook.com/docs/instagram-platform/sharing-to-stories/).
