### ISSUE TITLE
Sharing options not showing on android 12

### ISSUE THREAD

**Issue by fellipesnoww** [react-native-share/react-native-share#1284]
Hello guys!
I have a doubt.

Sharing options are not showing on devices with ANDROID 12 or higher.

But has anyone had this problem? How can I solve?

**Comment by mikehardy** [comment]
Going to assume it is this: 
https://react-native-share.github.io/react-native-share/docs/install/#adding-queries-for-the-android-necessary-for-sdk--30

**Comment by hotaryuzaki** [comment]
> Hello guys! I have a doubt.
> 
> Sharing options are not showing on devices with ANDROID 12 or higher.
> 
> But has anyone had this problem? How can I solve?

same issue, just android 12.

> Going to assume it is this: https://react-native-share.github.io/react-native-share/docs/install/#adding-queries-for-the-android-necessary-for-sdk--30

so it means we have to add a lot of apps name that we will consider it will be showing in the shareSingle??
ex: com.instagram.android, com.facebook.katana, com.whatsapp

so that will be huge problem because we dont know what apps user installed

**Comment by mikehardy** [comment]
Then don't share single, just use "share". If you just use "share" the user gets to pick from all installed apps.

If you use share single this module first checks to see if the app is installed before attempting it (since it would fail otherwise...) but if you don't have the specific app in the list of specific apps you can check for the system won't show you it's installation status.

It's an android restriction, so no complaints here matter, you could complain to google but they did it on purpose for privacy reasons. You must adapt and move on

**Comment by hotaryuzaki** [comment]
im sorry my bad, yes you are right maybe i just use Share.open function.

but at first i have a problem for android 12 for this function either, so my share icon not showing anyhing.i've installed with APK.
