### ISSUE TITLE
Share.shareSingle(iOS)for twitter posts url instead of .mp4 file

### ISSUE THREAD

**Issue by freeze1131** [react-native-share/react-native-share#1285]
In Android, following options works perfectly, but on iOS, it posts the url.
This is the local file that im trying to post.

/var/mobile/Containers/Data/Application/A0D33702-7DE2-493E-88F8-2C533B38F59D/Documents/RNFetchBlob_tmp/RNFetchBlobTmp_qht4mv1a1dr5xgcq5xb4kx.mp4

Options for Twitter

let shareOptionsTwitter = {
  social:Share.Social.TWITTER,
  url:videoUrl,
  type:'*/*'
};

**Comment by VTSingle** [comment]
same issue with image. @freeze1131 if you will find any solution - pls notify me.

**Comment by VTSingle** [comment]
@freeze1131 looks like I found solution 

So we found a workaround for the shareSingle with Twitter, by changing a little piece of code in GenericShare.m from the package:

Line 20:

From that:

    if(![serviceType isEqualToString:@"com.apple.social.twitter"] && [[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:inAppBaseUrl]]) {
To:

    if([serviceType isEqualToString:@"com.apple.social.twitter"] && [[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:inAppBaseUrl]]) {
Just remove the exclamation mark after the if.

This is probably a temporary fix, but it works for now.

**Comment by freeze1131** [comment]
@VTSingle I tried it and it opens the tweet window but does not attach the .mp4 file now. But now I got the shareResponse now which is {"message": "", "success": true}, before that I couldn't get that message at all.

**Comment by VTSingle** [comment]
@freeze1131 it's work for me with image, but now facebook is broke (( 

If anyone has variants - pls provide

**Comment by Erbaz** [comment]
Having a similar issue but with image files (JPEG) on Android. Message gets shared but no image is being shown on post

At first I thought this issue was due to image aspect ratios. However this issue was only occurring for the image when using the `share.open()` function.

It seems like a package issue whereby there is a deprecated identifier. Needs to be fixed soon.

**Comment by mikehardy** [comment]
@Erbaz 

> Needs to be fixed soon.

Hop right on that, we'll merge your PR - https://medium.com/digitalfrontiers/5-reasons-why-you-should-contribute-to-open-source-projects-2f65443b4077 vs https://medium.com/hackernoon/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b

**Comment by freeze1131** [comment]
@VTSingle no I did not. Tried to work with GenericShare.m but couldn't make it. I am using share.open() for twitter share right now.

**Comment by Erbaz** [comment]
> @Erbaz share.open() works for both Android and iOS. But when i try to share with shareSingle() on iOS, it posts url. Also on iOS, whatsApp sharesingle with local mp4 file does not work.

My issue has been resolved and I have to say it was completely unrelated to the package. It was actually that the base64 string was incorrectly being generated at an earlier stage because I accidentally encoded an already encoded URI.  Just had to remove one of the encoding functions and it got fixed.

**Comment by meetwithtaha01** [comment]
@freeze1131 did you find the solution for single share ?

**Comment by geroale** [comment]
Same issue here
