### ISSUE TITLE
"error": "Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference"

### ISSUE THREAD

**Issue by akinkarayun** [react-native-share/react-native-share#1298]

**Comment by mikehardy** [comment]
Please format your code so others may read it - triple-backticks and the javscript specifier should help

```javascript
 // like this formatted comment here
```

**Comment by YuriLima23** [comment]
Well after many hours i find the problem 

<img width="1244" height="217" alt="Image" src="https://github.com/user-attachments/assets/d96ffb51-f03a-4bea-bf0a-55cfd8017f18" />

From what I understand, the library is looking for the file in the wrong location, and it seems like some permission is missing. So, if you use Expo's FileSystem or another tool that downloads the file and places it, for example, in the DOCUMENTS folder, it won’t work because the library won’t be able to access this file. To make it work, you’ll need to place it in the app’s Cache folder and define pathname, type, and url.

<img width="934" height="90" alt="Image" src="https://github.com/user-attachments/assets/682b698d-ebce-4e1e-8576-9d2b7dbe4911" />


When I manage to fix it, I’ll open a PR to address both the validations (to prevent the error) and the share_download_paths.xml configuration, which appears to be the actual source of the problem.

<img width="888" height="118" alt="Image" src="https://github.com/user-attachments/assets/2ce01648-38d6-4c3a-84e1-ff93e52c873d" />

**Comment by ahtokca** [comment]
Go the same issue Android 35 and rn-share v12.2.0.

**Comment by AlexKyrdyukov** [comment]
change from 

      const logFile = `${RNFS.DocumentDirectoryPath}/app.log`;

to

      const logFile = `${RNFS.CachesDirectoryPath}/app.log`;

        url: `file://${logFile}`,

**Comment by infini-te** [comment]
I am getting same issue:

```bash
ERROR while sharing the doc [Error: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference]
```

```js
 await Share.open({
       url: `file://${uri}`,
       type: 'application/pdf',
   });
```

### Value of `uri`
```bash
 /storage/emulated/0/Android/data/com.nareemobileapp.dev/files/Documents/MedicalRecord.pdf
```

### Environment:
Android 35 && RN v0.77
