### ISSUE TITLE
Update react-native at example app to 0.6X

### ISSUE THREAD

**Issue by MateusAndrade** [react-native-share/react-native-share#1310]
### Steps to reproduce
Following the update published for react-native, the `android_build` is not working. To fix that, we need to push a update for the example app in order to fix the build problem.

We can look at the details here: https://github.com/facebook/react-native/issues/35210

### Expected behaviour
- Android app should build at CircleCI.

### Actual behaviour
- Android app build is broken at CircleCI.

**Comment by mikehardy** [comment]
Hey :wave: - given that my refresh-example scripted example app rebuild style is not integrated here and given that maintaining example apps is a ridiculous waste of time for maintainers, in general, this appears to be the real forward-looking solution:

https://github.com/microsoft/react-native-test-app

The only downside I'm aware of is that it does not appear to support web :thinking: ? Or did not last I checked. Then again, I don't think this module does either

I've got a dormant PR for the same in the netinfo repository from one of the RN-test-app maintainers and I'm excited to try it but haven't found the time yet despite it being open since March !

https://github.com/react-native-netinfo/react-native-netinfo/pull/582
