### ISSUE TITLE
Not able to share image on linkedIn on iOS

### ISSUE THREAD

**Issue by Hamza6244** [react-native-share/react-native-share#1322]
### Steps to reproduce
I'm using **share.open** method for sharing content on social media platforms.
```
const shareOptions = {
  title: "Share Image",
  message: "",
  url: image64,
  failOnCancel: false,
};
try {
  await Share.open(shareOptions);
  console.log("file shared successfully");
} catch (error) {
  console.log("Error =>", error);
}
```

### Expected behaviour
After using above method i should able to see the linkedIn share option from dialogue prompt and image should be share on the LinkedIn.

### Actual behaviour
When i'm passing base64 in url then linkedIn share option is not showing in dialogue box. But when i'm passing message param also with url then linkedIn option is visible but image is still not sharing on linkedIn.

### Environment
react-native - **0.67.3**:
- **iOS Version**: 15.7

### react-native-share
**^8.0.0**
npm version : 8.19.2"

### Link to repo
https://github.com/react-native-share/react-native-share

**Comment by nikitph** [comment]
Any update on this

**Comment by mikehardy** [comment]
We merge all reasonable PRs
Most issues have no update without them

In either case, it's fully open on github, there will be no updates without you personally moving it forward with either the detailed results of your research or your PR - in the general sense of "you" that is you personally @nikitph plus any future person that reads this

**Comment by nikitph** [comment]
Perhaps this should go on the documentation or the issue templates that any
shortcomings or bugs in this library should be fixed by the issue creators
themselves. The maintainers will be focused on merging the relevant changes
after review.

These unsaid rules or processes in someones mind are not obvious to
everybody. There is some super work that has been done in the library and
its perfectly natural to for it to have some shortcomings which can be
resolved with decent discussion.

**Comment by nikitph** [comment]
@Hamza6244 were you able to resolve this via any method not documented on the repo?

**Comment by mikehardy** [comment]
@nikitph if you think that belongs somewhere, you can also propose a PR to the docs / issue template :laughing: :pray: 

It's just general rules in almost *all* open source repos. Open source means, in general: if you care about it, you code it or fix it. The word "should" when used in the context that someone else "should" do something, has negative value since people take time to read the words but nothing actually happens

**Comment by yasir-syed** [comment]
Any update? What is the workaround

**Comment by symentix-khushbu** [comment]
what is the solution for this  issue?
