### ISSUE TITLE
IOS , sharesheet not opening , it closes immediately,

### ISSUE THREAD

**Issue by doshishreyansh** [react-native-share/react-native-share#1330]
### Steps to reproduce

https://user-images.githubusercontent.com/114562284/207578618-135cf79e-8d93-4d44-9e8d-c36a9a4c0ca8.mov

### Actual behaviour
Share.open(options) ,closing immediately on ios 

### XCODE response
[ShareSheet] connection invalidated

### Environment
- **React Native version**:"0.70.6"
- **React Native platform + platform version**: iOS 16.1

### react-native-share
**Version**: "^7.3.9"

**Comment by ansh** [comment]
Just use `Share` from `react-native` instead? I think it will do what you want.

`import { Share } from "react-native"`

**Comment by doshishreyansh** [comment]
> Just use `Share` from `react-native` instead? I think it will do what you want.
> 
> `import { Share } from "react-native"`

I tried both of them, issue also exist in import { Share } from "react-native

**Comment by ansh** [comment]
That means the issue is in your code. You’re probably updating state constantly. Share your whole file’s code here.

**Comment by mikehardy** [comment]
This will be a project-specific problem and not result in any change in this module, so it is not an issue we'll keep open.

You can examine the example app or docs for appropriate usage and prove it works by just doing a simple App.js that does a simple share as a test demonstrating it works.

**Comment by ghasemikasra39** [comment]
I have the same issue on version `8.2.0`. Any solution?

**Comment by mikehardy** [comment]
@ghasemikasra39 with the information provided? No, there is no solution

**Comment by anferrat** [comment]
I came across similar problem, It has something to do with overflow menu, when I hide my menu right after (or before) calling open sheet method the sheet get dismissed right away, because the menu view gets dismounted. Seems like that when Share.open method (or even Share.share from rn) is appearing during dismounting of the menu, it gets dismissed. One way to solve it is to wait for Share.open response and then hide the menu. Or you can play with setTimeout, to call Share.open after 200-300 ms after hiding the menu, it also seemed to work for me. RN 0.72.1
