### ISSUE TITLE
[IOS] Share.shareSingle, Share twitter with image cant typing text

### ISSUE THREAD

**Issue by Poovit-B** [react-native-share/react-native-share#1379]
https://user-images.githubusercontent.com/61401085/228135827-81201c94-a2b0-47fb-9dbf-b4b8d29e6c54.mp4

```
      const options = {
        title: message,
        message: message,
        type: 'image/*',
        social: Share.Social?.[social],
      }

      const file = await handleCapture()
      options.url = `file://${file?.path}`

      await Share.shareSingle(options);
```
      
### Environment
- **React Native version**: 0.70.6
- **React Native platform**: IOS

**Comment by majih93** [comment]
have you been able to solve this problem? I wonder if this problem is related to this library, or to the twitter api itself.

**Comment by nbutmickey** [comment]
i met the same problem, any soulutions @codeflows

**Comment by DipoAreoye** [comment]
Same problem here

**Comment by mikehardy** [comment]
On the contrary, it's open source and it was just sitting there since July with no one apparently interested enough to investigate and/or propose a PR. That is the definition of stale

In open source things don't just happen - you are the library developer not just the user. If something is important, allocate resources and do the diagnostics + fixes resulting in a PR
