### ISSUE TITLE
Android - react-native-share throws "User did not share" error when successfully sharing via gmail app

### ISSUE THREAD

**Issue by sam1463** [react-native-share/react-native-share#1390]
### Steps to reproduce
1. Open the share modal using the following code on android:
```
        try {
            const result = await Share.open({
                message: 'text here',
            });
        } catch (e) {
            // ends up here with 'User did not share'
        }
2. share the message via gmail
3. see an error instead of success

### Expected behaviour
Tell us what should happen
The result should be a success

### Actual behaviour
Tell us what happens instead
It throws an error

### Environment
- **React Native version**: 0.70.8
- **React Native platform + platform version**: Android 13 
- **Typescript version** (if using typescript): 4.9.5

### react-native-share
**Version**: 8.2.2

### Notes
We are experiencing this in an app using expo (but not expo go)

**Comment by richardkuiper** [comment]
Having the same issue. Anyone found any solutions yet?

**Comment by namikarif** [comment]
Having the same issue. Anyone found any solutions yet?

**Comment by namikarif** [comment]
Having the same issue

**Comment by AlkanV** [comment]
i have same problem, do we have any possible solution for this?

**Comment by richardkuiper** [comment]
Turns out I was having this issue on iOS, not on Android. 

The problem I was having is that I was trying to share an image and the image was stored in a private directory on the device that seemed inaccessible. This was confirmed when I could share text successfully.

I did the following to resolve my issue:

1. Switched to [expo-share](https://docs.expo.dev/versions/latest/sdk/sharing/)
2. Copied the image over to a cache directory and shared that instead.

**Comment by thinhph-tech** [comment]
I found the issue resultCode always return 0 in onActivityResult,  document android  said:  output of action_send have nothing

**Comment by jsg2021** [comment]
> I found the issue resultCode always return 0 in onActivityResult, document android said: output of action_send have nothing

This seems to be a pervasive issue... I had to disable `failOnCancel` for android

**Comment by Gavru4** [comment]
Same problem
