### ISSUE TITLE
Sharing video to Instagram story works on iOS but not android

### ISSUE THREAD

**Issue by davidwinograd1** [react-native-share/react-native-share#1464]
### Steps to reproduce
This is my code:

```
const shareToInstagramStories = async (bite) => {
    const shareOptions = {
      backgroundVideo: bite.url,
      type: 'video/mp4',
      social: Share.Social.INSTAGRAM_STORIES,
      appId: //appId here, 
      forceDialog: true,
      useInternalStorage: true,
    };

    Share.shareSingle(shareOptions)
      .then((res) => {
        console.log(res);
      })
      .catch((err) => {
        console.error(err);
      });
  };
```

### Expected behavior
Should work on both iOS and Android

### Actual behavior
Only works on iOS

### Environment
- **React Native version**: 0.68.7
- **React Native platform + platform version**: All Android
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?

### react-native-share
**Version**: npm version or "master"
9.4.1

### Link to repo (highly encouraged)
https://github.com/

**Comment by bszyman** [comment]
Funny.

I came here because it seems like Share.Social.INSTAGRAM_STORIES no longer works when I test on iOS (not tested on Android yet).

It seems like the standard Share.Social.INSTAGRAM option takes users to a unified screen where the user can select if the media goes to a story or a reel or a message.

I was wondering if Share.Social.INSTAGRAM_STORIES was even needed any more.

Here's what Share.Social.INSTAGRAM looks like for me:

![image](https://github.com/react-native-share/react-native-share/assets/2079918/fee17734-0216-4899-b770-1741c8d822d6)
