### ISSUE TITLE
couldn't find key url in dynamic object getString     ReadableNativeMap.java:-2 getFileShare

### ISSUE THREAD

**Issue by NawazKhanMd** [react-native-share/react-native-share#392]
When Share.open is called application crashes with this exception 

![image](https://user-images.githubusercontent.com/15027672/47480044-ab6d9600-d84c-11e8-904e-60c99311c6ff.png)

```
couldn't find key url in dynamic object
getString
    ReadableNativeMap.java:-2
getFileShare
    ShareIntent.java:74
open
    ShareIntent.java:37
open
    GenericShare.java:18
open
    RNShareModule.java:50
invoke
    Method.java:-2
invoke
    BaseJavaModule.java:345
invoke
    JavaModuleWrapper.java:136
run
    NativeRunnable.java:-2
handleCallback
    Handler.java:789
dispatchMessage
    Handler.java:98
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:164
run
    MessageQueueThreadImpl.java:196
run
    Thread.java:764
```

**Comment by NawazKhanMd** [comment]
@jgcmarins

**Comment by jgcmarins** [comment]
which version?

**Comment by NawazKhanMd** [comment]
if I update either of these, every other thing breaks

**Comment by NawazKhanMd** [comment]
it was working fine without any error

Suddenly this error popped out
after so many tries i could get one file share
but multi file share gives the above error

**Comment by mikehardy** [comment]
I think you can upgrade gradle and still use the older react-native if you just apply the workaround for bundle creation / packaging on android release apps - I do this and just have a "bundle" step I do before packaging android prod, it looks like this in my package.json and just does the same bundle the normal metro packager from react-native does, but in advance:

```
    "android-bundle": "node node_modules/react-native/local-cli/cli.js bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/",
```

(it's my understanding this is only necessary because gradle now has a slightly deeper "build/intermediates" hierarchy that includes a "releases" subdirectory that the react-native gradle code had to be updated to handle)
