### ISSUE TITLE
What is "Share Single" category ?

### ISSUE THREAD

**Issue by vikjovanov** [react-native-share/react-native-share#798]
Hello,

when I go to the "Share Single" category in the documentation, I realize that there is a list of applications supported by the react-native-share package. 

So, to start with, I was already wondering what "Share Single" meant exactly. I didn't really understand the associated example gifs.

Then, why are some applications, like FACEBOOK_STORIES, only supported on iOS and others only on Android? What's that due to ? 
Does this mean that I won't be able to share an image in a facebook storie from an android phone?

Thanks for your answers
Viktor

**Comment by MateusAndrade** [comment]
HI @vikjovanov , thanks for sharing this with us. The purpose of `Share.single` is to share to a specific application, instead of calling the generic "share". 

Wich may work as a "deep link".  Also, some implementation is only supported in specific platforms(Facebook Stories for example), but you still able to call `Share.open` to share with these platforms.

Also, sorry for the confusion with our "docs", I have been working on a newer version and I would be glad if you can check it out. 😅

**Comment by Osamasomy** [comment]
Im using latest version "react-native-share": "^3.7.0"  which works fine but then Im using **Share.single** (according to the doc) its not working **reactNativeShare.default.single is not a function**.
After Some Searching  I replace **Share.single** with **shareSingle** and now its work fine.
Please Update  Doc or Guide me.

**Comment by MateusAndrade** [comment]
> Im using latest version "react-native-share": "^3.7.0" which works fine but then Im using **Share.single** (according to the doc) its not working **reactNativeShare.default.single is not a function**.
> After Some Searching I replace **Share.single** with **shareSingle** and now its work fine.
> Please Update Doc or Guide me.

Thanks for sharing that. PRS updating/fixing the docs are always welcome. Let me know if there is anything that I can help you.
