### ISSUE TITLE
Please make it Expo compatible

### ISSUE THREAD

**Issue by sunviwo** [react-native-share/react-native-share#840]
## Describe the Feature
Please make this package compatible with Expo. Obviously it is more advance than Expo Sharing API. Please make it support Expo to let beginners as me take advantage of its feature while we are learning how to develop non-expo projects. Thanks

**Comment by MateusAndrade** [comment]
Hi @sunviwo. Can you share the problems that you are facing when trying to use this library with expo? This would help us improve this project.

**Comment by sunviwo** [comment]
Thank you @MateusAndrade. To begin with, the installation procedure can't be applied for Expo, as there is no MainApplication.java and gradle to edit in Expo, especially in [managed workflow](https://docs.expo.io/introduction/managed-vs-bare/).

**Comment by MarlonX19** [comment]
not working on Expo...!

**Comment by mikehardy** [comment]
PRs happily accepted...! (it's open source, it could be you that makes it work)

**Comment by taeh98** [comment]
> PRs happily accepted...! (it's open source, it could be you that makes it work)

I would be very happy to contribute to making this library compatible with Expo's managed workflow. Apart from anything else, it would be useful for my own project. I have no idea how you would do that though.

**Comment by mikehardy** [comment]
@taeh98 I don't know either unfortunately, I think bare workflow would be easier but for managed workflow expo typically has some module in their unimodule system already available? That might be easier. If not, then I would fall back on finding some/any other module that is also expo compatible and trying to pattern off that

**Comment by pr0da** [comment]
Yeah, they have an `expo-sharing` module, but that's pretty limited. IMO this package would be a way better alternative.
Unfortunately because of the native deps I think this is more like a decision on the expo team's side. Afaik they basically have to add the native deps to the expo sdk/"shell". You can vote on the [feature request](https://expo.canny.io/feature-requests/p/support-for-react-native-share) or maybe submit a PR to the expo repo.

I'm talking about the managed workflow, in bare workflow I don't think there's any difference compared to a simple react native project.

**Comment by taeh98** [comment]
> 
> 
> Yeah, they have an `expo-sharing` module, but that's pretty limited. IMO this package would be a way better alternative.
> Unfortunately because of the native deps I think this is more like a decision on the expo team's side. Afaik they basically have to add the native deps to the expo sdk/"shell". You can vote on the [feature request](https://expo.canny.io/feature-requests/p/support-for-react-native-share) or maybe submit a PR to the expo repo.
> 
> I'm talking about the managed workflow, in bare workflow I don't think there's any difference compared to a simple react native project.

Yeah, I think that's all true. I've [added a feature request](https://expo.canny.io/feature-requests/p/document-how-to-make-libraries-compatible-with-expo) to document what exactly makes a library compatible with Expo in the managed workflow and how to implement it for existing libraries, because I think it would be useful to know for sure.

**Comment by Fedeorlandau** [comment]
Re-opening this. Would love to use this on expo.

**Comment by mikehardy** [comment]
@Fedeorlandau that's not how it works really. PRs would be interesting though...

**Comment by anthlasserre** [comment]
If you want to use it with an Expo managed workflow project. Here is a feature request to support the integration easily.

https://github.com/react-native-share/react-native-share/pull/1606
