### ISSUE TITLE
Share not working when try share to instagram app using "share.open"

### ISSUE THREAD

**Issue by allandallopez** [react-native-share/react-native-share#923]
when i try to run :

```
import Share from 'react-native-share'

optionShare = async () => {
      const { imageURL } = this.state
      const shareOptions = {
         message: 'example message'
         url: `file://${imageURL}`,
      }

      try {
         const ShareResponse = await Share.open(shareOptions)
         console.log(JSON.stringify(ShareResponse))
      } catch (error) {
         console.log('debug:error', error)
      }
   }
```

its working properly until i choose share to instagram app, and iam getting alert like this :
 
![Image from iOS](https://user-images.githubusercontent.com/45220508/101730326-69674300-3aec-11eb-9514-c6a449dbadab.jpg)

i think this is not coming from the catch section. Need help

Environment & Version :
Iphone Device => IOS 14.2
React Native => 0.63.3

Note : this is working fine on the IOS version 12

**Comment by xrzhuang** [comment]
I am having the same problem!!!

**Comment by redko-o** [comment]
Same issue

**Comment by fatihyildizhan** [comment]
same issue

**Comment by encored-gujung** [comment]
I solved it by passing base64 data in url

```js
    const base64Image = await RNFS.readFile(uri, 'base64');
    await Share.open({
      url: `data:image/png;base64, ${base64Image}`,
      ...shareOptions,
    });
```

**Comment by fatihyildizhan** [comment]
@encored-gujung It says 'open' does not exists. There is only Share.share()

<img width="550" alt="share" src="https://user-images.githubusercontent.com/602600/103189077-19ee8880-48dc-11eb-9b22-917487786cbb.png">

**Comment by pr0da** [comment]
@fatihyildizhan Are you sure you are not using Share from `react-native` by accident?

**Comment by mikeho** [comment]
Workaround provided @encored-gujung works, with two caveats:

- I'd suggest using something like react-native-mime-types to lookup the MIME, instead of hard-coding "image/png"
- Unfortunately, this doesn't seem to work at all for Video files

I tried a number of different things to try and get it to work for Video files, but it doesn't seem to work at all... in fact, the IG icon doesn't even show up at all on the Share Action Sheet when attempting to share a video file.

Any thoughts would be greatly appreciated... thanks!
