### ISSUE TITLE
shareSingle not working as expected on android

### ISSUE THREAD

**Issue by Kesmek** [react-native-share/react-native-share#951]
Using `Share.open(url: URL)` works as intended with the apps available to share to but calling `shareSingle(url: URL, social: ...)` with most of the available social platforms (facebook, twitter, Linkedin, etc.) does not work as intended. The success callback is returned with `{"app": null, "message": true}` and instead of redirecting me to the relevant app, my photo library is instead brought up.

Here is an example of how I am using shareSingle:
```
const shareTwitter = async () => {
    const options = {
      social: Share.Social.TWITTER,
      url: uri,
      message: "Test message",
      title: "Share via",
    };

    try {
      const result = await Share.shareSingle(options);
      console.log("result:", result);
    } catch (err) {
      console.log(err);
    }
  };
```
This exact format (without the "social" field) works as intended with Share.open(options).

### Steps to reproduce
1. Save a video locally (format: "file:///...")
2. Call shareSingle(url: URL, social: ...) with appropriate uri
3. Success callback is returned with `{"app": null, "message": true}` and photo gallery is opened

### Expected behaviour
The appropriate social media app in `"social": Share.Social.APP` should be opened with the file ready to share in it.

### Actual behaviour
The photo library is opened and the success callback is returned

### Environment
- **React Native version**: 0.63.3
- **React Native platform + platform version**: Android 11

### react-native-share
**Version**: 5.1.0

**Comment by mrarronz** [comment]
Can you try add `forceDialog: true` to the options? using v5.1.0

This issue also happens to me, after I read the android native code, I found that there is a `forceDialog` param, but not mentioned in any doc. I tried to add it to share options, and it did work. I have tested facebook, twitter and instagram, all of them can be opened, not sure for other social apps.

**Comment by Kesmek** [comment]
> Can you try add `forceDialog: true` to the options? using v5.1.0
> 
> This issue also happens to me, after I read the android native code, I found that there is a `forceDialog` param, but not mentioned in any doc. I tried to add it to share options, and it did work. I have tested facebook, twitter and instagram, all of them can be opened, not sure for other social apps.

While adding this certainly returns a more informative dialog 
`result: {"app": "com.google.android.apps.photos/com.google.android.apps.photos.pager.HostPhotoPagerActivity", "message": true}`, 
the underlying issue of not being redirected to the proper application remains. Using this option still redirects me to the photos app as seen in the above return statement.

**Comment by mrarronz** [comment]
I have successfully opened the facebook, twitter and instagram when sharing an image, but the email box cannot be opened. The `type` param is also needed if you are sharing an image, e.g
```
this.viewShotRef.capture().then((uri: string) => {
      const imageData = `data:image/png;base64,${uri}`;
      const shareOptions = {
        url: imageData,
        message: "",
        social: social,
        type: "image/jpeg"
      };
      Share.shareSingle(shareOptions).catch(() => {
      });
    });
```
@Kesmek Maybe you can try `filename` instead of `url` for your local file. Since you are sharing a video, I think the `type` param should be something like `type: "video/mp4"`or `type: "video/*"`. [https://stackoverflow.com/questions/43224261/share-video-from-android-app](https://stackoverflow.com/questions/43224261/share-video-from-android-app), have a try and good luck.

You need to read the native code to figure out whether this library can achieve this because there are no documentations for some code changes. I think the best solution for sharing is integrating SDKs of all the social platforms you want, with their own sharing APIs, this would be the most effective way.

**Comment by kp72-dev** [comment]
android 6.0 still not able to share on facebook

**Comment by PhongTV97** [comment]
I still have same issue. Can you help me?
