### ISSUE TITLE
Unable to shareSingle to insta story on android - Parcel is a null object reference

### ISSUE THREAD

**Issue by devpascoe** [react-native-share/react-native-share#954]
**iOS working fine.**

### Steps to reproduce
1. standard android setup
2. basic code to share to instagram story

```
      const shareOptions = {
        method: IGShare.InstagramStories.SHARE_BACKGROUND_AND_STICKER_IMAGE,
        backgroundImage: backgroundImageUrl,
        stickerImage: stickerUrl,
        social: IGShare.Social.INSTAGRAM_STORIES,
      }
      await IGShare.shareSingle(shareOptions)
```

### Expected behaviour
Tell us what should happen
launch insta story screen

### Actual behaviour
Tell us what happens instead
Receive error
```{"error": "Attempt to invoke virtual method 'void android.net.Uri.writeToParcel(android.os.Parcel, int)' on a null object reference"}```

### Environment
- **React Native version**: 0.63.3
- **React Native platform + platform version**: Android 6.0.1

### react-native-share
**Version**: 5.1.0

Note: Instagram is installed on device.

**Comment by devpascoe** [comment]
Running same app in simulator API 27 i get: ```Attempt to invoke virtual method 'java.lang.String.android.net.Uri.getScheme()' on a null object reference```

**Comment by devpascoe** [comment]
Ok so a few things. I didn't realise from the documentation that you can't use external urls (well unofficially it seems to work on iOS, not android). So instead using a file:// from a saved image i am able use that without error.

However on my older android device i just get a screen flash and it returns to my app (no insta launched). Same happened when trying with another library so i assume that's got to do with my device.

This discussion and code block (especially the normalisation method) gave me some clues.
https://github.com/react-native-share/react-native-share/issues/808#issuecomment-668741231

**Comment by piotrekzawada** [comment]
I'm having similar issue with `singleShare` on android. I'm using `"react-native-share": "^5.1.4",` and `"react-native": "0.63.2",`. 

So my issue is that i'm getting this response from shareSingle: `res {"app": "CANCELED", "message": false}`

Following code works on iOS but does not work on android:
```
try {
  const shareOptions = {
     stickerImage: image, // base64 image
     social: Share.Social.INSTAGRAM_STORIES,
     method: Share.InstagramStories.SHARE_STICKER_IMAGE,
     backgroundTopColor: '#000',
     backgroundBottomColor: '#1300e8',
     forceDialog: true,
   };

  const res = await Share.shareSingle(shareOptions);
  console.log('res', res);
} catch (e) {
  console.log('e', e);
}
```
Even though I have `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` in AndroidManifest.xml. 

I've tried workaround from [#808 (comment)](https://github.com/react-native-share/react-native-share/issues/808#issuecomment-668741231). Using `open` also **works** in my case [#808 (comment)](https://github.com/react-native-share/react-native-share/issues/808#issuecomment-791526373).

I'm getting this error in logcat: 
`Could not dispatch action since the SDK service is disabled X.1PB: The Zero SDK service is not enabled`

**Comment by fatihyildizhan** [comment]
I have the same issue. I upgraded to v6.0.1 TypeScript, still couldn't fix it.

**Comment by dylan-westbury** [comment]
Experiencing same flash @devpascoe
