### ISSUE TITLE
When sharing image+message on Telegram only image is shared

### ISSUE THREAD

**Issue by luandro** [react-native-share/react-native-share#966]
### Steps to reproduce
1. Use the `Share.open(options)` function with options:
```json
 {
   "failOnCancel": false,
   "message": "Here's a message 
              17 de fev. de 2021 11:21  
              UTM 2929 559828 82828282

             rest of message",
   "subject": "Alert",
   "urls": ["file:///data/user/0/com.myapp/files/media/preview/31/3194c0b168ea037658f1ce3d17eb9b5f.jpg"]
}

```

2. Select Telegram to share

### Expected behaviour
Expect both image and message to be shared.

### Actual behaviour
Only image is shared.

### Environment
- **React Native version**: 0.63.2
- **React Native platform + platform version**: Android 6.0

### react-native-share
**Version**: 5.1.1

### Link to repo (highly encouraged)
https://github.com/digidem/mapeo-mobile

**Comment by douglasbraz** [comment]
I has same problem, but in IOS. Any sugestion?

**Comment by luandro** [comment]
Tried digging the Java files to find anything relevant, but couldn't find anything. Could someone point us to where relevant logic might be?

**Comment by antoinedelp** [comment]
We have the same problem for Facebook and LinkedIn on Android. When removing the picture, the text shows up. Impossible to have both image and text for now.

**Comment by kaioduarte** [comment]
I did some testing by sharing an image with caption from WhatsApp to Telegram, Twitter, LinkedIn, Instagram, and Facebook.

- Telegram and Twitter works with a single image, so pass `url` instead of `urls`.
- LinkedIn, Facebook and, Instagram just share the image. I couldn't find any docs about sharing both text and image through Intents.

cc @antoinedelp @douglasbraz
